services:

  celery-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A services.tasks worker --loglevel=info
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    env_file:
      - ../.env
    volumes:
      - redis_data:/data
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
