"""add migrations

Revision ID: 1b65e7570eae
Revises: 4a6d73cc01ef
Create Date: 2025-01-13 03:33:17.705353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b65e7570eae'
down_revision: Union[str, None] = '4a6d73cc01ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transaction', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='unique')
    # ### end Alembic commands ###
